# This workflow will build and push a .NET Core app to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net60&pivots=development-environment-vscode
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and DOTNET_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: Build and deploy ASP.Net Core app to an Azure Web App
on:
  push:
    branches: [ "dev", "qa", "main" ]
  workflow_dispatch:
  # Setting an environment variable with the value of a configuration variable
        

permissions:
  contents: read
env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '9.0.0'      

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ contains(github.ref, 'dev') && 'dev' ||
        contains(github.ref, 'main') && 'production' ||
        contains(github.ref, 'qa') && 'qa' }}
    steps:
    - name: Detect Environment
      run: echo "Deploying to ${{ github.ref }} → ${{ env.ENVIRONMENT }}"
    - name: Print Environment-Specific Variables
      run: |
          # Access variables from the environment using the `vars` context
          echo "DEMO variable: ${{ vars.DEMO }}"
          # Secrets are masked but can be used in scripts (not printed)
          echo "Secret status: [HIDDEN]"
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Extract some files
      run: 7z x build.zip  
    - name: List files
      run: |
        echo "Files in the repository:"
        ls -R
    - name: Detect Environment
      run: echo "Deploying to ${{ github.ref }} → ${{ env.ENVIRONMENT }}"
    - name: List files
      run: |
        echo "Files in the repository:"
        ls -R
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: pkchaipoc001
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/build
