# This workflow will build and push a .NET Core app to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-dotnetcore?tabs=net60&pivots=development-environment-vscode
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the AZURE_WEBAPP_PACKAGE_PATH and DOTNET_VERSION environment variables below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: Build and deploy ASP.Net Core app to an Azure Web App
on:
  push:
    branches: [ "dev", "qa", "main" ]
  workflow_dispatch:
  # Setting an environment variable with the value of a configuration variable
        

permissions:
  contents: read
env:
  env_var: ${{ vars.ENV_CONTEXT_VAR }}
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '9.0.0'
  USERNAME: 'maneesh'
  USER_EMAIL: 'memaneesh@hotmail.com'
  TARGET_REPO: "https://github.com/msingh025/angular-http-guide.git" 
  TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
  TARGET_REPO_BRANCH: 'dev'
  DEPLOYMENT_ENVIRONMENT: ${{ github.ref == 'refs/heads/dev' && 'dev' ||
    github.ref == 'refs/heads/main' && 'production' ||
    github.ref == 'refs/heads/qa' && 'qa' }}
  RUNNER_ENVIRONMENT: ${{ github.ref == 'refs/heads/dev' && 'ubuntu-latest' ||
      github.ref == 'refs/heads/main' && 'ubuntu-latest' ||
      github.ref == 'refs/heads/qa' && 'ubuntu-latest' || 'ubuntu-latest' }}
  
jobs:
  build:
    runs-on: ${{ github.ref == 'refs/heads/dev' && 'ubuntu-latest' ||
      github.ref == 'refs/heads/main' && 'ubuntu-latest' ||
      github.ref == 'refs/heads/qa' && 'ubuntu-latest' || 'ubuntu-latest' }}
    environment:
      name: ${{ github.ref == 'refs/heads/dev' && 'dev' ||github.ref == 'refs/heads/main' && 'production' ||github.ref == 'refs/heads/qa' && 'qa' }}
    steps:
    - name: Detect Environment
      run: echo "Runner information $RUNNER_ENVIRONMENT"   "Deploying to ${{ github.ref }} → ${{ env.DEPLOYMENT_ENVIRONMENT }}" 
    - name: Print Environment-Specific Variables
      run: |
          # Access variables from the environment using the `vars` context
          echo "DEMO variable: ${{ vars.DEMO }} and  deployment var: ${{ env.DEPLOYMENT_ENVIRONMENT }}"
          # Secrets are masked but can be used in scripts (not printed)
          echo "Secret status: [HIDDEN]"
          echo "MY_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Extract some files
      run: 7z x build.zip  
    - name: List files
      run: |
        echo "Files in the repository:"
        ls -R
    - name: Detect Environment
      run: echo "Deploying to ${{ github.ref }} → ${{ env.ENVIRONMENT }}"
    - name: Configure Git
      run: |
          git config --global user.name "${{env.USERNAME}}"
          git config --global user.email "${{env.USER_EMAIL}}"
          
          git clone --depth 1 --branch $TARGET_REPO_BRANCH \
          "https://${{ secrets.TARGET_REPO_PAT }}@github.com/msingh025/angular-http-guide.git" target-repo
    - name: Make Changes in Target Repo
      working-directory: ./target-repo
      run: |
          echo "Updated at $(date)" >> timestamp.txt
          git add .
          git commit -m "Auto-update from source repo: $(date)"
    - name: Push Changes to Target Repo
      working-directory: ./target-repo
      run: |
          git push origin $TARGET_BRANCH
    - name: List files
      run: |
        echo "Files in the repository:"
        ls -R
    - name: Lgin to Azure
      uses: azure/login@v2
      with: 
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Key Vault
      id: keyvault
      uses: azure/get-keyvault-secrets@v1
      with:
        azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
        keyvault: 'pkchaivault'
        secrets: 'demoKeyVaultSecret'
    - name: List of Key Vault Secrets
      run: |
        echo "Key Vault Secrets:"
        echo "${{ steps.keyvault.outputs.pkchaivault }}"
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: pakage_version_${{ env.MY_DATE }}
        path: build.zip 
        retention-days: 5

    # - name: Update environment variables
    #   run: |
    #       # Get current settings
    #       # Optional: Add secret from GitHub Secrets
    #       az webapp config appsettings set \
    #         --name $AZURE_WEBAPP_NAME \
    #         --resource-group $RESOURCE_GROUP \
    #         --settings \
    #           SECRET_API_KEY="${{ secrets.API_KEY }}" \
    #           DATABASE_URL="${{ secrets.DB_CONNECTION_STRING }}"
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: pkchaipoc001
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/build
    - name: update heathcheck
      run: |
        k=$(az resource update --resource-group $RESOURCE_GROUP --name $AZURE_WEBAPP_NAME --resource-type "Microsoft.Web/sites" --set properties.siteConfig.healthCheckPath="/health")
        # az resource update \
        #  --resource-group $RESOURCE_GROUP \
        #  --name $AZURE_WEBAPP_NAME \
        #  --resource-type "Microsoft.Web/sites" \
        #  --set properties.siteConfig.healthCheckPath="/api/Todo" \
        #  --api-version "2018-02-01"