name: Static Choice Example
on:
  push:
    branches: [ "dev", "qa", "main" ]
  workflow_dispatch:
    inputs:
      enableFeatureX:
        description: 'Enable feature X'
        required: true
        default: 'staging'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use selected enableFeatureX
        run: echo "Deploying to ${{ github.event.inputs.enableFeatureX }}"